language: cpp

dist: xenial
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-4.8
      env: COMPILER=g++-4.8
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-3.5
             - ubuntu-toolchain-r-test
          packages:
             - clang++-3.5
             - libc++-dev
      env: COMPILER=clang++-3.5
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-3.6
             - ubuntu-toolchain-r-test
          packages:
             - clang++-3.6
             - libc++-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-3.7
             - ubuntu-toolchain-r-test
          packages:
             - clang++-3.7
             - libc++-dev
      env: COMPILER=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-3.8
             - ubuntu-toolchain-r-test
          packages:
             - clang++-3.8
             - libc++-dev
      env: COMPILER=clang++-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang++-3.9
            - libc++-dev
      env: COMPILER=clang++-3.9


install:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script: mkdir build && cd build && cmake .. && make && ./tests
